---
apiVersion: v1
kind: Service
metadata:
  name: grpc-auth
spec:
  type: ClusterIP
  selector:
    app: grpc-auth
  ports:
  - port: 3000
    name: http-grpc-auth
    targetPort: http-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-auth
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: grpc-auth
  template:
    metadata:
      labels:
        app: grpc-auth
    spec:
      containers:
      - name: grpc-auth
        image: devsecopsandres/test #alicewasko/grpcauth-v3:0.1
        env:
          - name: PROJECT_ID
            valueFrom:
              secretKeyRef:
                name: authv3secret
                key: PROJECT_ID
          - name: SERVICE_ACCOUNT_ID
            valueFrom:
              secretKeyRef:
                name: authv3secret
                key: SERVICE_ACCOUNT_ID
        imagePullPolicy: Always
        ports:
        - name: http-api
          containerPort: 3000
        resources:
          limits:
            cpu: "0.1"
            memory: 100Mi